### ISSUE TITLE
Some hooks should run on whole file, not just changed lines

### ISSUE THREAD

**Issue by lencioni** [causes/overcommit#136]
There are some rules in ESLint and JSHint (and likely other linters) that operate on the whole file. Because overcommit is only running on the changed lines here, we are missing some problems at pre-commit time.

For instance, say I have the following file:

```js
const $ = require('jquery');
...
$('.my-selector').hide();
...
```

Now, say I remove the last use of `$` but forget to remove the definition at the top:

```js
const $ = require('jquery');
...
```

ESLint will complain:

> $ is defined but never used (no-unused-vars) [javascript/eslint]

However, overcommit does not catch this because it is only looking at modified lines.

@jawshooah it looks like you've worked on these hooks recently. Any thoughts?

**Comment by sds** [comment]
Just to clarify: the hooks will still run on the entire file. It's the lines for which errors/warnings are reported that determine whether overcommit reports an error/warning.

If you want to treat errors as problems regardless of whether they were on modified lines, you should set the `problem_on_unmodified_line` option for the hook to `report` (see https://github.com/causes/overcommit#hooks for details).

**Comment by lencioni** [comment]
Ah! I see. And it looks like that is set to `warn` as the default for all pre-commit hooks too: https://github.com/causes/overcommit/blob/74c74e6b1cb8ceb1cfc61da8c636dce989934a70/config/default.yml#L57

What do you think about elevating this to `report` for EsLint and JsHint?

**Comment by jawshooah** [comment]
I'm not sure how I feel about setting that as a default, since the vast majority of errors are local to modified lines. I don't want to be unable to commit without fixing someone else's trivial, unrelated style error.

**Comment by sds** [comment]
I don't have strong opinions about this, but the problem with keeping the default as `warn` is the possibility of hiding warnings that were introduced by the commit. For example, when adding too many lines to the end of a method, `rubocop`'s `MethodLength` will report a problem but Overcommit will treat it as a warning since the reported line is the method signature, not the actual contents that were added to the method.

Enabling this on a case-by-case basis might also be confusing. If we're going to change this, we should perhaps switch the default to be `report` for all hooks, and let developers opt-in to more relaxed enforcement. I would personally prefer this than maintaining `warn` as the default, as it encourages you to clean up all the mistakes in your codebase, and is what you would want anyway if you're using Overcommit in CI runs via `overcommit --run` (which is something I think should be encouraged).

**Comment by jawshooah** [comment]
I see your point; defaulting to the stricter option is probably better. Though `overcommit --run` already considers all lines to be modified, so that's not really relevant here.

**Comment by lencioni** [comment]
> For example, when adding too many lines to the end of a method, rubocop's MethodLength will report a problem but Overcommit will treat it as a warning since the reported line is the method signature, not the actual contents that were added to the method.

Yes, this is exactly the same as my example. I'm mostly tired of thinking that everything is good in a chain of commits and then when I push to code review I see that I did something dumb that overcommit should have warned me about, but I didn't notice because it didn't prevent my commit.

I think elevating the default level makes sense, especially because it is so easy to just run `SKIP=all git commit` if the hooks fail and you decide to commit anyway.

Some possible alternatives or additions to just increasing the default level:

- I typically don't ever even notice overcommit's warnings, so it might be helpful to include some information about the warnings in the summary at the end that usually says "All pre-commit hooks passed". Maybe "All pre-commit hooks passed but there were # warnings." and use yellow instead of green.
- We could be more aggressive and add a prompt if there are only warnings, asking the user if they want to abort the commit or not. "There were # warnings. Do you want to abort the commit? (y/n) [y]:" Similarly, we could show this prompt for regular errors that would normally abort the commit.
- We could allow hooks to specify a function that would determine which problems should `warn` or `report` on unmodified lines. This would allow each hook to opt in to the stricter behavior for specific rules where the problem might be the result of your change while keeping the noise level down. The downside is it sounds somewhat complex, labor-intensive and error-prone to set up properly, and require a fair amount of maintenance. In the end, I think I'd rather just raise the default level.

**Comment by lencioni** [comment]
> Though `overcommit --run` already considers all lines to be modified, so that's not really relevant here.

I think @sds's point is that if you are using `overcommit --run` in CI, then it would be nice if the pre-commit hooks warned you about the same problems to prevent you from pushing commits that will fail once they are in CI.

**Comment by jawshooah** [comment]
Agreed. If the checks pass locally, you should expect them to pass in a CI environment.

> We could allow hooks to specify a function that would determine which problems should `warn` or `report` on unmodified lines.

I like this idea. It's unobtrusive, in that it doesn't affect existing hooks, and it leaves room for those hooks to be refined with stricter reporting.

> The downside is it sounds somewhat complex, labor-intensive and error-prone to set up properly, and require a fair amount of maintenance.

I'm not so sure. In most cases, it would probably just be a regex comparison. Something like

```ruby
REPORT_MESSAGE_REGEX = /
  Method too long |
  Unused variable |
/ix

def handle_unmodified_line(type, line, message)
  return :report if type == :error || message =~ REPORT_MESSAGE_REGEX
  :warn
end
```

**Comment by sds** [comment]
I'm hesitant to implement a solution that requires code to be written in order to turn on/off errors for certain messages. This usually results in many pull requests down the road as tools inevitably change and either add new types of errors or change the wording of existing error messages. Having to commit a change to Overcommit to fix these cases as they arise is not a good long-term decision.

I also don't like the complexity this potentially introduces. Instead of being able to think in very black and white terms of `report` or `warn` on unmodified lines, one now needs context to know in what situations a error or warning will be reported (especially if we start doing this on a case-by-case basis).

Regarding:

> I typically don't ever even notice overcommit's warnings, so it might be helpful to include some information about the warnings in the summary at the end that usually says "All pre-commit hooks passed". Maybe "All pre-commit hooks passed but there were # warnings." and use yellow instead of green.

I think this is a good idea, and have added a feature request in #137.

Regarding:
> We could be more aggressive and add a prompt if there are only warnings, asking the user if they want to abort the commit or not. "There were # warnings. Do you want to abort the commit? (y/n) [y]:" Similarly, we could show this prompt for regular errors that would normally abort the commit.

Overcommit will never support inline prompts, since git hooks don't have access to the STDIN stream/TTY the developer is using (and it's not guaranteed that this stream will always exist, since you hooks can be triggered via executing `git` in scripts).

**Comment by sds** [comment]
Just circling back on this: I've changed default value of `problem_on_unmodified_line` from `warn` to `report` in ded2b4671eb913140c6b85792721529f4778decb. I think this will be the right choice going forward, as it's simple enough for users to disable it be setting the option in their `ALL` hook back to `warn`, e.g.

```yaml
PreCommit:
  ALL:
    problem_on_unmodified_line: warn
```
