### ISSUE TITLE
Problems with the TravisLint hook

### ISSUE THREAD

**Issue by deivid-rodriguez** [causes/overcommit#153]
I'm trying to add _overcommit_ to [byebug](https://github.com/deivid-rodriguez/byebug) but I'm having problems with the `TravisLint` hook.

This is [the diff](https://gist.github.com/deivid-rodriguez/b28650631a02cd5448bd#file-diff) that's supposed to add _overcommit_ (I'm changing the `.travis.yml` just to force the hook to be run).

This is [the segfault](https://gist.github.com/deivid-rodriguez/b28650631a02cd5448bd#file-segfaults-by-default) I'm getting by default and this is [the error](https://gist.github.com/deivid-rodriguez
/b28650631a02cd5448bd#file-error-with-custom-command) I get if I add the custom command `command: bundle exec travis` to the `.overcommit.yml` file

If I run `travis lint` by itself (both with and without _bundler_), I get the expected output:

    $ travis lint
    Warnings for .travis.yml:
    [x] your repository must be feature flagged for the os setting to be used
    $ bundle exec travis lint
    Warnings for .travis.yml:
    [x] your repository must be feature flagged for the os setting to be used

**Comment by sds** [comment]
Hey @deivid-rodriguez, thanks for your interest in `overcommit`!

Unfortunately, because the segfault is happening entirely within the `travis` gem's code, I wouldn't have any idea how to help you solve that particular problem.

However, I can tell you that the `command` option must be given an array of arguments, not a single string. So if you set the command to `command: ['bundle', 'exec', 'travis']` it should work.

See `haml-lint`'s [`.overcommit.yml`](https://github.com/causes/haml-lint/blob/master/.overcommit.yml) and [`.travis.yml`](https://github.com/causes/haml-lint/blob/master/.travis.yml) for an example of a configuration that uses `overcommit --run` in CI.

Hope that helps!

**Comment by deivid-rodriguez** [comment]
@sds I thought it would be _overcommit_'s problem because running `travis` by itself would just work.

Thanks for the configuration tip. Diagonal reading is a bad thing: I grepped `bundle` in your README, found the `command` setting and show `bundle exec rubocop` in the right side, so I used that... :S

Fixing the configuration now gives me this error:

    Running pre-commit hooks
    Checking for trailing whitespace.................[TrailingWhitespace] OK
    Checking Travis CI configuration.........................[TravisLint] FAILED
    /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/spec_set.rb:85:in `map!'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/spec_set.rb:85:in `materialize'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/definition.rb:132:in `specs'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/definition.rb:177:in `specs_for'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/definition.rb:166:in `requested_specs'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/environment.rb:18:in `requested_specs'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/runtime.rb:13:in `setup'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler.rb:122:in `setup'
	    from /home/davidr/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.1/lib/bundler/setup.rb:18:in `<top (required)>'
	    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    Checking YAML syntax.....................................[YamlSyntax] OK

Now it's entirely inside bundler but It seems that in both cases _overcommit_ wants to use system's Ruby, which is ' 1.9.1', so everything is messed up.

**Comment by jawshooah** [comment]
This may be a silly question, but do you have `travis` listed in your Gemfile?

**Comment by sds** [comment]
@deivid-rodriguez from that stack trace it's not using the system Ruby, but 2.2.1. It's bundler 1.9.1 that is being invoked, which I'm pretty sure is unrelated to this issue.

The issue is that `rake` cannot be found within the Bundler context you are invoking `travis` in. Are your gems being cached as part of your Travis build? Perhaps you have rake 10.4.1 cached and so you need to force a reinstall. Since you are invoking `travis` in a Bundler context, Bundler errors when you try to access a library that isn't specified as a dependency in your Gemfile.

**Comment by deivid-rodriguez** [comment]
@sds Nope, no caching involved... Notice that I'm getting the error in my local environment, not in travis. Doesn't this path point to system's ruby stuff?

    /usr/lib/ruby/1.9.1/rubygems/custom_require.rb

@jawshooah Yes, look at the diff linked in my first post.

**Comment by sds** [comment]
Try running `bundle exec overcommit --run` in your repository and see what happens.

I don't use `rvm`, so I can't offer an explanation of why the beginning of your stack trace is in the system Ruby.

**Comment by sds** [comment]
Perhaps when you installed overcommit with `gem install overcommit`, you didn't activate the correct version of ruby, and now anytime you run `overcommit` it's using the version that was installed in the system version instead of your desired Ruby version?

**Comment by deivid-rodriguez** [comment]
Thanks for your help guys!

So the problem seems to have to do with [hub](https://github.com/github/hub/). I was aliasing `hub` to `git`. After removing that alias, everything works as expected. 

I'll open an issue in _hub_ and link here.

**Comment by jawshooah** [comment]
Strange, I have the same alias and I haven't had any problems. Glad you
figured it out, though!

**Comment by deivid-rodriguez** [comment]
@jawshooah Let's see if it gets fixed! Thanks for the support!
