### ISSUE TITLE
Hooks for commands outside cross-platform package managers

### ISSUE THREAD

**Issue by jawshooah** [causes/overcommit#99]
What is the policy regarding hooks that depend on executables not available through `gem`, `npm`, `pip`, etc? Are such hooks permissible in the core set?

For example, I'd like to submit a pre-commit hook for `scalastyle`, which is available as an executable for Mac users with `brew install scalastyle`, but Windows and Linux users must download the jarfile and use `java -jar scalastyle-batch-<version>.jar` to run it.

**Comment by sds** [comment]
Thanks for asking a great question, @jawshooah.

Such hooks are fine, but you shouldn't bother specifying `install_command` in its default configuration, since there's no general installation method that works on all platforms.

While it hasn't been an issue, I think we would start to draw the line if a particular tool doesn't seem to have significant adoption or much of a community behind it. That's pretty open to interpretation, but we'd rather of more hooks contributed at this point in time. 

In this case, `scalastyle` seems like a worthwhile addition. A pull request would be welcome!
